### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Flomp**

### CODE REVIEW

**Comment by xamax71** [comment]
Hey, Nice project!
I'm currently testing it as a possible alternative to Komoot.
I can take care of the Italian translation. 
Could not find the file on Crowdin and seems that I cannot create one.

**Comment by BastLast** [comment]
> Hey, Nice project! I'm currently testing it as a possible alternative to Komoot. I can take care of the Italian translation. Could not find the file on Crowdin and seems that I cannot create one.

only admin on crowdin can add languages to a project

**Comment by BastLast** [comment]
protip with crowdin if you don't want to fix the conflict you can just delete this PR and branch and crowdin sill recreate it conflict free

**Comment by xamax71** [comment]
> > Hey, Nice project! I'm currently testing it as a possible alternative to Komoot. I can take care of the Italian translation. Could not find the file on Crowdin and seems that I cannot create one.
> 
> only admin on crowdin can add languages to a project

Maybe you can add it? So I can translate it :)

**Comment by BastLast** [comment]
> > > Hey, Nice project! I'm currently testing it as a possible alternative to Komoot. I can take care of the Italian translation. Could not find the file on Crowdin and seems that I cannot create one.
> > 
> > only admin on crowdin can add languages to a project
> 
> Maybe you can add it? So I can translate it :)
> Merci pour ton aide !

I am not an admin on this project, just another random coming by and liking the project i just know from other projects

**Comment by xamax71** [comment]
> > > > Hey, Nice project! I'm currently testing it as a possible alternative to Komoot. I can take care of the Italian translation. Could not find the file on Crowdin and seems that I cannot create one.
> > > 
> > > 
> > > only admin on crowdin can add languages to a project
> > 
> > 
> > Maybe you can add it? So I can translate it :)
> > Merci pour ton aide !
> 
> I am not an admin on this project, just another random coming by and liking the project i just know from other projects



> _ No description provided. _

Any change (or interest) to add the Italian file so that I can translate it? Thanks

**Pull request closed without merging**
